services:
  app:
    build: .
    environment:
      - MYSQL=mysql://root:mysql@db/app
    ports:
      - 3000:3000
    restart: always
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=app

    volumes:
        - db-data:/var/lib/mysql
    restart: always
volumes:
  db-data:
  uploads: